[package]
name = "dbase-scraper-rust"
version = "0.1.0"
authors = ["Salvador Guzman <guzmansalv@gmail.com>"]

[[bin]]
name = "dbase-scraper-rust"
path = "./src/main.rs"

[dependencies]
postgres = "0.15.2"
rand = "0.5.5"
reqwest = "0.9.2"
scraper = "0.7.0"
